const jobsList = [
  {
    id: 1,
    jobTitle: "Kitchen Porter",
    location: "Manchester",
    amount: 11.5,
    startDate: "2024-08-15",
    endDate: "2024-08-20",
    totalEstimatedPay: 575,
    jobDescription: [
      "Clean and sanitize kitchen equipment and surfaces",
      "Wash dishes, utensils, and cookware",
      "Assist with food preparation tasks",
      "Maintain cleanliness of storage areas",
      "Dispose of waste according to health and safety guidelines",
      "Assist chefs and kitchen staff as needed",
      "Ensure compliance with food safety regulations",
    ],
    agencyName: "CulinaryStaff Ltd",
    dresscode: "Chef whites and non-slip shoes",
    industry: "Catering",
    role: "Kitchen Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 2,
    jobTitle: "Care Assistant",
    location: "Birmingham",
    amount: 12.75,
    startDate: "2024-08-18",
    endDate: "2024-09-01",
    totalEstimatedPay: 1785,
    jobDescription: [
      "Assist residents with daily living activities",
      "Monitor and record patients' conditions",
      "Administer medication as prescribed",
      "Provide emotional support and companionship",
      "Maintain a clean and safe environment",
      "Collaborate with healthcare professionals",
      "Respond to emergencies following established protocols",
    ],
    agencyName: "CarePlus Staffing",
    dresscode: "Scrubs and comfortable shoes",
    industry: "Care",
    role: "Healthcare Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 3,
    jobTitle: "Warehouse Operative",
    location: "Leeds",
    amount: 10.5,
    startDate: "2024-08-20",
    endDate: "2024-09-10",
    totalEstimatedPay: 1680,
    jobDescription: [
      "Pick and pack orders accurately and efficiently",
      "Use handheld devices for inventory management",
      "Operate forklifts and pallet jacks safely",
      "Maintain a clean and organized warehouse",
      "Perform quality checks on outgoing shipments",
      "Assist with loading and unloading trucks",
      "Follow all safety procedures and guidelines",
    ],
    agencyName: "LogiStaff Solutions",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Logistics Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 4,
    jobTitle: "Event Steward",
    location: "London",
    amount: 11.25,
    startDate: "2024-08-25",
    endDate: "2024-08-26",
    totalEstimatedPay: 225,
    jobDescription: [
      "Guide and assist attendees at large-scale events",
      "Ensure crowd safety and manage queues",
      "Check tickets and control access points",
      "Respond to inquiries and provide event information",
      "Report any security concerns or incidents",
      "Assist with emergency procedures if needed",
      "Maintain a professional and friendly demeanor",
    ],
    agencyName: "EventPro Staffing",
    dresscode: "Black trousers, white shirt, and comfortable shoes",
    industry: "Events",
    role: "Customer Service",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 5,
    jobTitle: "Production Line Operator",
    location: "Bristol",
    amount: 11.0,
    startDate: "2024-09-01",
    endDate: "2024-09-30",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Operate and monitor production machinery",
      "Assemble products according to specifications",
      "Perform quality control checks",
      "Maintain a clean and safe work area",
      "Report any equipment malfunctions",
      "Follow production schedules and targets",
      "Adhere to all safety protocols and procedures",
    ],
    agencyName: "IndustriHire",
    dresscode: "Provided uniform and safety shoes",
    industry: "Manufacturing",
    role: "Production Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 6,
    jobTitle: "Retail Assistant",
    location: "Glasgow",
    amount: 10.75,
    startDate: "2024-09-05",
    endDate: "2024-09-20",
    totalEstimatedPay: 1290,
    jobDescription: [
      "Assist customers with product selection",
      "Operate cash registers and process transactions",
      "Maintain store cleanliness and organization",
      "Restock shelves and update product displays",
      "Handle customer inquiries and complaints",
      "Participate in inventory counts",
      "Ensure proper pricing and labeling of products",
    ],
    agencyName: "RetailPro Staffing",
    dresscode: "Black trousers and company-provided shirt",
    industry: "Retail",
    role: "Sales Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 7,
    jobTitle: "Office Administrator",
    location: "Edinburgh",
    amount: 12.5,
    startDate: "2024-09-10",
    endDate: "2024-10-10",
    totalEstimatedPay: 2500,
    jobDescription: [
      "Manage office communications and correspondence",
      "Schedule appointments and maintain calendars",
      "Prepare and organize documents and reports",
      "Handle basic bookkeeping and data entry tasks",
      "Greet visitors and answer phone calls",
      "Coordinate office supplies and equipment maintenance",
      "Assist with various administrative projects as needed",
    ],
    agencyName: "AdminPlus Recruitment",
    dresscode: "Business casual",
    industry: "Administrative",
    role: "Office Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 8,
    jobTitle: "Bartender",
    location: "Liverpool",
    amount: 11.75,
    startDate: "2024-09-15",
    endDate: "2024-09-30",
    totalEstimatedPay: 1410,
    jobDescription: [
      "Prepare and serve alcoholic and non-alcoholic beverages",
      "Take customer orders and process payments",
      "Maintain cleanliness of bar area and equipment",
      "Check identification to ensure legal drinking age",
      "Monitor customer alcohol consumption",
      "Restock bar supplies and manage inventory",
      "Ensure compliance with health and safety regulations",
    ],
    agencyName: "NightLife Staffing",
    dresscode: "Black trousers, white shirt, and black apron",
    industry: "Hospitality",
    role: "Bar Staff",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 9,
    jobTitle: "Security Guard",
    location: "Newcastle",
    amount: 12.0,
    startDate: "2024-09-20",
    endDate: "2024-10-20",
    totalEstimatedPay: 2880,
    jobDescription: [
      "Monitor and patrol assigned areas",
      "Control access to premises and check credentials",
      "Respond to alarms and investigate disturbances",
      "Write detailed incident reports",
      "Operate security equipment such as CCTV",
      "Perform security checks and risk assessments",
      "Liaise with police and emergency services when necessary",
    ],
    agencyName: "SecureForce Ltd",
    dresscode: "Provided uniform and comfortable shoes",
    industry: "Security",
    role: "Safety Personnel",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 10,
    jobTitle: "Delivery Driver",
    location: "Cardiff",
    amount: 11.25,
    startDate: "2024-09-25",
    endDate: "2024-10-25",
    totalEstimatedPay: 2700,
    jobDescription: [
      "Deliver packages to residential and commercial addresses",
      "Plan efficient routes using GPS technology",
      "Load and unload vehicles safely",
      "Collect signatures and payments for deliveries",
      "Maintain accurate records of deliveries and vehicle conditions",
      "Adhere to traffic laws and company safety policies",
      "Provide excellent customer service during deliveries",
    ],
    agencyName: "Swift Logistics",
    dresscode: "Company-provided uniform and comfortable shoes",
    industry: "Transportation",
    role: "Logistics Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 11,
    jobTitle: "Call Center Representative",
    location: "Sheffield",
    amount: 11.0,
    startDate: "2024-10-01",
    endDate: "2024-11-01",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Handle incoming customer calls and inquiries",
      "Provide information about products and services",
      "Process orders and resolve customer complaints",
      "Update customer accounts and maintain records",
      "Meet performance metrics for call handling",
      "Collaborate with other departments to resolve issues",
      "Participate in ongoing training and quality improvement",
    ],
    agencyName: "TelePro Staffing",
    dresscode: "Business casual",
    industry: "Customer Service",
    role: "Call Center Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 12,
    jobTitle: "Housekeeping Attendant",
    location: "Brighton",
    amount: 10.5,
    startDate: "2024-10-05",
    endDate: "2024-10-20",
    totalEstimatedPay: 1260,
    jobDescription: [
      "Clean and prepare guest rooms and public areas",
      "Change linens and make beds",
      "Restock amenities and supplies",
      "Report maintenance issues to appropriate staff",
      "Ensure security of guest rooms",
      "Follow proper cleaning protocols and safety procedures",
      "Respond to guest requests in a timely manner",
    ],
    agencyName: "HospitalityPro",
    dresscode: "Provided uniform and comfortable shoes",
    industry: "Hospitality",
    role: "Housekeeping",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 13,
    jobTitle: "Construction Laborer",
    location: "Belfast",
    amount: 12.25,
    startDate: "2024-10-10",
    endDate: "2024-11-10",
    totalEstimatedPay: 2940,
    jobDescription: [
      "Assist skilled workers with various construction tasks",
      "Operate hand and power tools safely",
      "Load and unload construction materials",
      "Clean and prepare construction sites",
      "Follow safety guidelines and wear protective equipment",
      "Assist with basic measurements and calculations",
      "Perform physical labor tasks as directed",
    ],
    agencyName: "BuildForce Recruitment",
    dresscode: "Hard hat, safety vest, and steel-toe boots",
    industry: "Construction",
    role: "General Labor",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 14,
    jobTitle: "Digital Marketing Assistant",
    location: "Oxford",
    amount: 13.0,
    startDate: "2024-10-15",
    endDate: "2024-11-15",
    totalEstimatedPay: 3120,
    jobDescription: [
      "Assist in creating and scheduling social media content",
      "Monitor social media channels and engage with audience",
      "Help with email marketing campaigns",
      "Conduct basic SEO tasks and keyword research",
      "Assist in creating reports on marketing metrics",
      "Support the development of marketing materials",
      "Stay updated on digital marketing trends and best practices",
    ],
    agencyName: "DigitalTalent Agency",
    dresscode: "Smart casual",
    industry: "Marketing",
    role: "Marketing Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 15,
    jobTitle: "Forklift Operator",
    location: "Southampton",
    amount: 12.5,
    startDate: "2024-10-20",
    endDate: "2024-11-20",
    totalEstimatedPay: 3000,
    jobDescription: [
      "Operate forklifts to move, locate, and stack materials",
      "Load and unload trucks and containers",
      "Perform daily equipment inspections",
      "Maintain inventory records and log activities",
      "Follow all safety procedures and guidelines",
      "Assist with general warehouse duties as needed",
      "Report any equipment issues or safety concerns",
    ],
    agencyName: "WarehousePro Staffing",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Material Handling",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 16,
    jobTitle: "Teaching Assistant",
    location: "Cambridge",
    amount: 11.75,
    startDate: "2024-10-25",
    endDate: "2024-12-20",
    totalEstimatedPay: 4230,
    jobDescription: [
      "Support teachers in classroom activities",
      "Assist students with individual and group work",
      "Prepare learning materials and set up equipment",
      "Supervise students during breaks and lunch times",
      "Help maintain a positive learning environment",
      "Assist with administrative tasks and record keeping",
      "Participate in staff meetings and training sessions",
    ],
    agencyName: "EduStaff Solutions",
    dresscode: "Smart casual",
    industry: "Education",
    role: "Classroom Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 17,
    jobTitle: "Barista",
    location: "York",
    amount: 10.75,
    startDate: "2024-11-01",
    endDate: "2024-11-30",
    totalEstimatedPay: 2580,
    jobDescription: [
      "Prepare and serve a variety of coffee drinks",
      "Take customer orders and process payments",
      "Maintain cleanliness of work area and equipment",
      "Restock supplies and manage inventory",
      "Provide excellent customer service",
      "Operate and clean coffee-making equipment",
      "Assist with food preparation as needed",
    ],
    agencyName: "CafeStaff Ltd",
    dresscode: "Black trousers, company-provided shirt, and apron",
    industry: "Food Service",
    role: "Barista",
    invitedMe: false,
    myAgency: true,
  },

  {
    id: 1,
    jobTitle: "Kitchen Porter",
    location: "Manchester",
    amount: 11.5,
    startDate: "2024-08-15",
    endDate: "2024-08-20",
    totalEstimatedPay: 575,
    jobDescription: [
      "Clean and sanitize kitchen equipment and surfaces",
      "Wash dishes, utensils, and cookware",
      "Assist with food preparation tasks",
      "Maintain cleanliness of storage areas",
      "Dispose of waste according to health and safety guidelines",
      "Assist chefs and kitchen staff as needed",
      "Ensure compliance with food safety regulations",
    ],
    agencyName: "CulinaryStaff Ltd",
    dresscode: "Chef whites and non-slip shoes",
    industry: "Catering",
    role: "Kitchen Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 2,
    jobTitle: "Care Assistant",
    location: "Birmingham",
    amount: 12.75,
    startDate: "2024-08-18",
    endDate: "2024-09-01",
    totalEstimatedPay: 1785,
    jobDescription: [
      "Assist residents with daily living activities",
      "Monitor and record patients' conditions",
      "Administer medication as prescribed",
      "Provide emotional support and companionship",
      "Maintain a clean and safe environment",
      "Collaborate with healthcare professionals",
      "Respond to emergencies following established protocols",
    ],
    agencyName: "CarePlus Staffing",
    dresscode: "Scrubs and comfortable shoes",
    industry: "Care",
    role: "Healthcare Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 3,
    jobTitle: "Warehouse Operative",
    location: "Leeds",
    amount: 10.5,
    startDate: "2024-08-20",
    endDate: "2024-09-10",
    totalEstimatedPay: 1680,
    jobDescription: [
      "Pick and pack orders accurately and efficiently",
      "Use handheld devices for inventory management",
      "Operate forklifts and pallet jacks safely",
      "Maintain a clean and organized warehouse",
      "Perform quality checks on outgoing shipments",
      "Assist with loading and unloading trucks",
      "Follow all safety procedures and guidelines",
    ],
    agencyName: "LogiStaff Solutions",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Logistics Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 4,
    jobTitle: "Event Steward",
    location: "London",
    amount: 11.25,
    startDate: "2024-08-25",
    endDate: "2024-08-26",
    totalEstimatedPay: 225,
    jobDescription: [
      "Guide and assist attendees at large-scale events",
      "Ensure crowd safety and manage queues",
      "Check tickets and control access points",
      "Respond to inquiries and provide event information",
      "Report any security concerns or incidents",
      "Assist with emergency procedures if needed",
      "Maintain a professional and friendly demeanor",
    ],
    agencyName: "EventPro Staffing",
    dresscode: "Black trousers, white shirt, and comfortable shoes",
    industry: "Events",
    role: "Customer Service",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 5,
    jobTitle: "Production Line Operator",
    location: "Bristol",
    amount: 11.0,
    startDate: "2024-09-01",
    endDate: "2024-09-30",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Operate and monitor production machinery",
      "Assemble products according to specifications",
      "Perform quality control checks",
      "Maintain a clean and safe work area",
      "Report any equipment malfunctions",
      "Follow production schedules and targets",
      "Adhere to all safety protocols and procedures",
    ],
    agencyName: "IndustriHire",
    dresscode: "Provided uniform and safety shoes",
    industry: "Manufacturing",
    role: "Production Support",
    invitedMe: false,
    myAgency: true,
  },
];

export { jobsList };
