import { faker } from "@faker-js/faker";

const generateJobSeekers = () => {
  const jobSeekers = [];

  for (let i = 0; i < 20; i++) {
    const jobSeeker = {
      firstName: faker.firstName(),
      lastName: faker.lastName(),
      email: faker.internet.email(),
      phoneNumber: faker.phone.phoneNumber(),
      profilePicture: faker.image.avatar(),
      dateOfBirth: faker.date
        .past(30, new Date("2000-01-01"))
        .toISOString()
        .split("T")[0],
      aboutMe: faker.lorem.sentences(3),
      totalJobsDone: faker.random.number({ min: 1, max: 100 }),
      withAgency: faker.random.boolean(),
      totalHoursWorked: faker.random.number({ min: 100, max: 5000 }),
      lastActiveDate: faker.date.recent().toISOString().split("T")[0],
      documents: [
        {
          documentName: "CV",
          lastUpdated: faker.date.past().toISOString().split("T")[0],
          documentUrl: faker.internet.url(),
        },
        {
          documentName: "International Passport",
          lastUpdated: faker.date.past().toISOString().split("T")[0],
          documentUrl: faker.internet.url(),
        },
        {
          documentName: "BRP",
          lastUpdated: faker.date.past().toISOString().split("T")[0],
          documentUrl: faker.internet.url(),
        },
        {
          documentName: "National Insurance",
          lastUpdated: faker.date.past().toISOString().split("T")[0],
          documentUrl: faker.internet.url(),
        },
      ],
      sharecode: faker.random.alphaNumeric(8),
      sharecodeExpiry: faker.date.future().toISOString().split("T")[0],
    };

    jobSeekers.push(jobSeeker);
  }

  return jobSeekers;
};

const jobsList = [
  {
    id: 1,
    jobTitle: "Kitchen Porter",
    location: "Manchester",
    amount: 11.5,
    startDate: "2024-08-15",
    endDate: "2024-08-20",
    totalEstimatedPay: 575,
    jobDescription: [
      "Clean and sanitize kitchen equipment and surfaces",
      "Wash dishes, utensils, and cookware",
      "Assist with food preparation tasks",
      "Maintain cleanliness of storage areas",
      "Dispose of waste according to health and safety guidelines",
      "Assist chefs and kitchen staff as needed",
      "Ensure compliance with food safety regulations",
    ],
    agencyName: "CulinaryStaff Ltd",
    dresscode: "Chef whites and non-slip shoes",
    industry: "Catering",
    role: "Kitchen Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 2,
    jobTitle: "Care Assistant",
    location: "Birmingham",
    amount: 12.75,
    startDate: "2024-08-18",
    endDate: "2024-09-01",
    totalEstimatedPay: 1785,
    jobDescription: [
      "Assist residents with daily living activities",
      "Monitor and record patients' conditions",
      "Administer medication as prescribed",
      "Provide emotional support and companionship",
      "Maintain a clean and safe environment",
      "Collaborate with healthcare professionals",
      "Respond to emergencies following established protocols",
    ],
    agencyName: "CarePlus Staffing",
    dresscode: "Scrubs and comfortable shoes",
    industry: "Care",
    role: "Healthcare Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 3,
    jobTitle: "Warehouse Operative",
    location: "Leeds",
    amount: 10.5,
    startDate: "2024-08-20",
    endDate: "2024-09-10",
    totalEstimatedPay: 1680,
    jobDescription: [
      "Pick and pack orders accurately and efficiently",
      "Use handheld devices for inventory management",
      "Operate forklifts and pallet jacks safely",
      "Maintain a clean and organized warehouse",
      "Perform quality checks on outgoing shipments",
      "Assist with loading and unloading trucks",
      "Follow all safety procedures and guidelines",
    ],
    agencyName: "LogiStaff Solutions",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Logistics Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 4,
    jobTitle: "Event Steward",
    location: "London",
    amount: 11.25,
    startDate: "2024-08-25",
    endDate: "2024-08-26",
    totalEstimatedPay: 225,
    jobDescription: [
      "Guide and assist attendees at large-scale events",
      "Ensure crowd safety and manage queues",
      "Check tickets and control access points",
      "Respond to inquiries and provide event information",
      "Report any security concerns or incidents",
      "Assist with emergency procedures if needed",
      "Maintain a professional and friendly demeanor",
    ],
    agencyName: "EventPro Staffing",
    dresscode: "Black trousers, white shirt, and comfortable shoes",
    industry: "Events",
    role: "Customer Service",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 5,
    jobTitle: "Production Line Operator",
    location: "Bristol",
    amount: 11.0,
    startDate: "2024-09-01",
    endDate: "2024-09-30",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Operate and monitor production machinery",
      "Assemble products according to specifications",
      "Perform quality control checks",
      "Maintain a clean and safe work area",
      "Report any equipment malfunctions",
      "Follow production schedules and targets",
      "Adhere to all safety protocols and procedures",
    ],
    agencyName: "IndustriHire",
    dresscode: "Provided uniform and safety shoes",
    industry: "Manufacturing",
    role: "Production Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 6,
    jobTitle: "Retail Assistant",
    location: "Glasgow",
    amount: 10.75,
    startDate: "2024-09-05",
    endDate: "2024-09-20",
    totalEstimatedPay: 1290,
    jobDescription: [
      "Assist customers with product selection",
      "Operate cash registers and process transactions",
      "Maintain store cleanliness and organization",
      "Restock shelves and update product displays",
      "Handle customer inquiries and complaints",
      "Participate in inventory counts",
      "Ensure proper pricing and labeling of products",
    ],
    agencyName: "RetailPro Staffing",
    dresscode: "Black trousers and company-provided shirt",
    industry: "Retail",
    role: "Sales Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 7,
    jobTitle: "Office Administrator",
    location: "Edinburgh",
    amount: 12.5,
    startDate: "2024-09-10",
    endDate: "2024-10-10",
    totalEstimatedPay: 2500,
    jobDescription: [
      "Manage office communications and correspondence",
      "Schedule appointments and maintain calendars",
      "Prepare and organize documents and reports",
      "Handle basic bookkeeping and data entry tasks",
      "Greet visitors and answer phone calls",
      "Coordinate office supplies and equipment maintenance",
      "Assist with various administrative projects as needed",
    ],
    agencyName: "AdminPlus Recruitment",
    dresscode: "Business casual",
    industry: "Administrative",
    role: "Office Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 8,
    jobTitle: "Bartender",
    location: "Liverpool",
    amount: 11.75,
    startDate: "2024-09-15",
    endDate: "2024-09-30",
    totalEstimatedPay: 1410,
    jobDescription: [
      "Prepare and serve alcoholic and non-alcoholic beverages",
      "Take customer orders and process payments",
      "Maintain cleanliness of bar area and equipment",
      "Check identification to ensure legal drinking age",
      "Monitor customer alcohol consumption",
      "Restock bar supplies and manage inventory",
      "Ensure compliance with health and safety regulations",
    ],
    agencyName: "NightLife Staffing",
    dresscode: "Black trousers, white shirt, and black apron",
    industry: "Hospitality",
    role: "Bar Staff",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 9,
    jobTitle: "Security Guard",
    location: "Newcastle",
    amount: 12.0,
    startDate: "2024-09-20",
    endDate: "2024-10-20",
    totalEstimatedPay: 2880,
    jobDescription: [
      "Monitor and patrol assigned areas",
      "Control access to premises and check credentials",
      "Respond to alarms and investigate disturbances",
      "Write detailed incident reports",
      "Operate security equipment such as CCTV",
      "Perform security checks and risk assessments",
      "Liaise with police and emergency services when necessary",
    ],
    agencyName: "SecureForce Ltd",
    dresscode: "Provided uniform and comfortable shoes",
    industry: "Security",
    role: "Safety Personnel",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 10,
    jobTitle: "Delivery Driver",
    location: "Cardiff",
    amount: 11.25,
    startDate: "2024-09-25",
    endDate: "2024-10-25",
    totalEstimatedPay: 2700,
    jobDescription: [
      "Deliver packages to residential and commercial addresses",
      "Plan efficient routes using GPS technology",
      "Load and unload vehicles safely",
      "Collect signatures and payments for deliveries",
      "Maintain accurate records of deliveries and vehicle conditions",
      "Adhere to traffic laws and company safety policies",
      "Provide excellent customer service during deliveries",
    ],
    agencyName: "Swift Logistics",
    dresscode: "Company-provided uniform and comfortable shoes",
    industry: "Transportation",
    role: "Logistics Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 11,
    jobTitle: "Call Center Representative",
    location: "Sheffield",
    amount: 11.0,
    startDate: "2024-10-01",
    endDate: "2024-11-01",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Handle incoming customer calls and inquiries",
      "Provide information about products and services",
      "Process orders and resolve customer complaints",
      "Update customer accounts and maintain records",
      "Meet performance metrics for call handling",
      "Collaborate with other departments to resolve issues",
      "Participate in ongoing training and quality improvement",
    ],
    agencyName: "TelePro Staffing",
    dresscode: "Business casual",
    industry: "Customer Service",
    role: "Call Center Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 12,
    jobTitle: "Housekeeping Attendant",
    location: "Brighton",
    amount: 10.5,
    startDate: "2024-10-05",
    endDate: "2024-10-20",
    totalEstimatedPay: 1260,
    jobDescription: [
      "Clean and prepare guest rooms and public areas",
      "Change linens and make beds",
      "Restock amenities and supplies",
      "Report maintenance issues to appropriate staff",
      "Ensure security of guest rooms",
      "Follow proper cleaning protocols and safety procedures",
      "Respond to guest requests in a timely manner",
    ],
    agencyName: "HospitalityPro",
    dresscode: "Provided uniform and comfortable shoes",
    industry: "Hospitality",
    role: "Housekeeping",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 13,
    jobTitle: "Construction Laborer",
    location: "Belfast",
    amount: 12.25,
    startDate: "2024-10-10",
    endDate: "2024-11-10",
    totalEstimatedPay: 2940,
    jobDescription: [
      "Assist skilled workers with various construction tasks",
      "Operate hand and power tools safely",
      "Load and unload construction materials",
      "Clean and prepare construction sites",
      "Follow safety guidelines and wear protective equipment",
      "Assist with basic measurements and calculations",
      "Perform physical labor tasks as directed",
    ],
    agencyName: "BuildForce Recruitment",
    dresscode: "Hard hat, safety vest, and steel-toe boots",
    industry: "Construction",
    role: "General Labor",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 14,
    jobTitle: "Digital Marketing Assistant",
    location: "Oxford",
    amount: 13.0,
    startDate: "2024-10-15",
    endDate: "2024-11-15",
    totalEstimatedPay: 3120,
    jobDescription: [
      "Assist in creating and scheduling social media content",
      "Monitor social media channels and engage with audience",
      "Help with email marketing campaigns",
      "Conduct basic SEO tasks and keyword research",
      "Assist in creating reports on marketing metrics",
      "Support the development of marketing materials",
      "Stay updated on digital marketing trends and best practices",
    ],
    agencyName: "DigitalTalent Agency",
    dresscode: "Smart casual",
    industry: "Marketing",
    role: "Marketing Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 15,
    jobTitle: "Forklift Operator",
    location: "Southampton",
    amount: 12.5,
    startDate: "2024-10-20",
    endDate: "2024-11-20",
    totalEstimatedPay: 3000,
    jobDescription: [
      "Operate forklifts to move, locate, and stack materials",
      "Load and unload trucks and containers",
      "Perform daily equipment inspections",
      "Maintain inventory records and log activities",
      "Follow all safety procedures and guidelines",
      "Assist with general warehouse duties as needed",
      "Report any equipment issues or safety concerns",
    ],
    agencyName: "WarehousePro Staffing",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Material Handling",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 16,
    jobTitle: "Teaching Assistant",
    location: "Cambridge",
    amount: 11.75,
    startDate: "2024-10-25",
    endDate: "2024-12-20",
    totalEstimatedPay: 4230,
    jobDescription: [
      "Support teachers in classroom activities",
      "Assist students with individual and group work",
      "Prepare learning materials and set up equipment",
      "Supervise students during breaks and lunch times",
      "Help maintain a positive learning environment",
      "Assist with administrative tasks and record keeping",
      "Participate in staff meetings and training sessions",
    ],
    agencyName: "EduStaff Solutions",
    dresscode: "Smart casual",
    industry: "Education",
    role: "Classroom Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 17,
    jobTitle: "Barista",
    location: "York",
    amount: 10.75,
    startDate: "2024-11-01",
    endDate: "2024-11-30",
    totalEstimatedPay: 2580,
    jobDescription: [
      "Prepare and serve a variety of coffee drinks",
      "Take customer orders and process payments",
      "Maintain cleanliness of work area and equipment",
      "Restock supplies and manage inventory",
      "Provide excellent customer service",
      "Operate and clean coffee-making equipment",
      "Assist with food preparation as needed",
    ],
    agencyName: "CafeStaff Ltd",
    dresscode: "Black trousers, company-provided shirt, and apron",
    industry: "Food Service",
    role: "Barista",
    invitedMe: false,
    myAgency: true,
  },

  {
    id: 1,
    jobTitle: "Kitchen Porter",
    location: "Manchester",
    amount: 11.5,
    startDate: "2024-08-15",
    endDate: "2024-08-20",
    totalEstimatedPay: 575,
    jobDescription: [
      "Clean and sanitize kitchen equipment and surfaces",
      "Wash dishes, utensils, and cookware",
      "Assist with food preparation tasks",
      "Maintain cleanliness of storage areas",
      "Dispose of waste according to health and safety guidelines",
      "Assist chefs and kitchen staff as needed",
      "Ensure compliance with food safety regulations",
    ],
    agencyName: "CulinaryStaff Ltd",
    dresscode: "Chef whites and non-slip shoes",
    industry: "Catering",
    role: "Kitchen Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 2,
    jobTitle: "Care Assistant",
    location: "Birmingham",
    amount: 12.75,
    startDate: "2024-08-18",
    endDate: "2024-09-01",
    totalEstimatedPay: 1785,
    jobDescription: [
      "Assist residents with daily living activities",
      "Monitor and record patients' conditions",
      "Administer medication as prescribed",
      "Provide emotional support and companionship",
      "Maintain a clean and safe environment",
      "Collaborate with healthcare professionals",
      "Respond to emergencies following established protocols",
    ],
    agencyName: "CarePlus Staffing",
    dresscode: "Scrubs and comfortable shoes",
    industry: "Care",
    role: "Healthcare Support",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 3,
    jobTitle: "Warehouse Operative",
    location: "Leeds",
    amount: 10.5,
    startDate: "2024-08-20",
    endDate: "2024-09-10",
    totalEstimatedPay: 1680,
    jobDescription: [
      "Pick and pack orders accurately and efficiently",
      "Use handheld devices for inventory management",
      "Operate forklifts and pallet jacks safely",
      "Maintain a clean and organized warehouse",
      "Perform quality checks on outgoing shipments",
      "Assist with loading and unloading trucks",
      "Follow all safety procedures and guidelines",
    ],
    agencyName: "LogiStaff Solutions",
    dresscode: "Steel-toe boots and high-visibility vest",
    industry: "Warehousing",
    role: "Logistics Support",
    invitedMe: false,
    myAgency: true,
  },
  {
    id: 4,
    jobTitle: "Event Steward",
    location: "London",
    amount: 11.25,
    startDate: "2024-08-25",
    endDate: "2024-08-26",
    totalEstimatedPay: 225,
    jobDescription: [
      "Guide and assist attendees at large-scale events",
      "Ensure crowd safety and manage queues",
      "Check tickets and control access points",
      "Respond to inquiries and provide event information",
      "Report any security concerns or incidents",
      "Assist with emergency procedures if needed",
      "Maintain a professional and friendly demeanor",
    ],
    agencyName: "EventPro Staffing",
    dresscode: "Black trousers, white shirt, and comfortable shoes",
    industry: "Events",
    role: "Customer Service",
    invitedMe: true,
    myAgency: false,
  },
  {
    id: 5,
    jobTitle: "Production Line Operator",
    location: "Bristol",
    amount: 11.0,
    startDate: "2024-09-01",
    endDate: "2024-09-30",
    totalEstimatedPay: 2640,
    jobDescription: [
      "Operate and monitor production machinery",
      "Assemble products according to specifications",
      "Perform quality control checks",
      "Maintain a clean and safe work area",
      "Report any equipment malfunctions",
      "Follow production schedules and targets",
      "Adhere to all safety protocols and procedures",
    ],
    agencyName: "IndustriHire",
    dresscode: "Provided uniform and safety shoes",
    industry: "Manufacturing",
    role: "Production Support",
    invitedMe: false,
    myAgency: true,
  },
];

const staffList = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "+44 7700 900123",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "+44 7700 900124",
    status: "pending",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phoneNumber: "+44 7700 900125",
    status: "inactive",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    phoneNumber: "+44 7700 900126",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@example.com",
    phoneNumber: "+44 7700 900127",
    status: "pending",
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    firstName: "Sarah",
    lastName: "Taylor",
    email: "sarah.taylor@example.com",
    phoneNumber: "+44 7700 900128",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    phoneNumber: "+44 7700 900129",
    status: "inactive",
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    firstName: "Emma",
    lastName: "Thomas",
    email: "emma.thomas@example.com",
    phoneNumber: "+44 7700 900130",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    firstName: "Daniel",
    lastName: "Jackson",
    email: "daniel.jackson@example.com",
    phoneNumber: "+44 7700 900131",
    status: "pending",
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    firstName: "Olivia",
    lastName: "White",
    email: "olivia.white@example.com",
    phoneNumber: "+44 7700 900132",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    firstName: "Matthew",
    lastName: "Harris",
    email: "matthew.harris@example.com",
    phoneNumber: "+44 7700 900133",
    status: "inactive",
    profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    firstName: "Sophia",
    lastName: "Martin",
    email: "sophia.martin@example.com",
    phoneNumber: "+44 7700 900134",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    firstName: "Andrew",
    lastName: "Thompson",
    email: "andrew.thompson@example.com",
    phoneNumber: "+44 7700 900135",
    status: "pending",
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    firstName: "Isabella",
    lastName: "Garcia",
    email: "isabella.garcia@example.com",
    phoneNumber: "+44 7700 900136",
    status: "active",
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    firstName: "Christopher",
    lastName: "Martinez",
    email: "christopher.martinez@example.com",
    phoneNumber: "+44 7700 900137",
    status: "inactive",
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];

const agencies = [
  {
    agencyName: "CulinaryStaff Ltd",
    address: "123 Catering Lane, London, W1T 3NL",
    email: "info@culinarystaff.com",
    phoneNumber: "+44 20 7123 4567",
    agencyBrief:
      "CulinaryStaff Ltd is a premier staffing agency specializing in the food service industry. We provide top-tier chefs, kitchen staff, and front-of-house personnel to restaurants, hotels, and catering companies across the UK. With our extensive network and rigorous vetting process, we ensure that our clients receive only the most skilled and professional staff for their culinary needs.",
    status: "Approved",
    primaryStaff: {
      firstName: "Gordon",
      lastName: "Ramsay",
      phoneNumber: "+44 7700 900138",
      email: "gordon.ramsay@culinarystaff.com",
    },
  },
  {
    agencyName: "CarePlus Staffing",
    address: "456 Wellness Road, Manchester, M1 1AD",
    email: "contact@careplus.co.uk",
    phoneNumber: "+44 161 234 5678",
    agencyBrief:
      "CarePlus Staffing is dedicated to providing compassionate and skilled healthcare professionals to hospitals, care homes, and private residences. Our team of nurses, care assistants, and support staff are thoroughly vetted and trained to deliver the highest standard of care. We prioritize both the wellbeing of our clients and the professional development of our staff.",
    status: "Approved",
    primaryStaff: {
      firstName: "Florence",
      lastName: "Nightingale",
      phoneNumber: "+44 7700 900139",
      email: "florence.nightingale@careplus.co.uk",
    },
  },
  {
    agencyName: "LogiStaff Solutions",
    address: "789 Warehouse Avenue, Birmingham, B1 1AA",
    email: "hello@logistaff.co.uk",
    phoneNumber: "+44 121 345 6789",
    agencyBrief:
      "LogiStaff Solutions is the go-to agency for logistics and warehousing personnel. We supply skilled workers for all aspects of the supply chain, from warehouse operatives to logistics managers. Our staff are trained in the latest warehouse management systems and safety protocols, ensuring efficient and safe operations for our clients.",
    status: "Pending",
    primaryStaff: {
      firstName: "Jack",
      lastName: "Forklift",
      phoneNumber: "+44 7700 900140",
      email: "jack.forklift@logistaff.co.uk",
    },
  },
  {
    agencyName: "EventPro Staffing",
    address: "101 Festival Street, Edinburgh, EH1 1AB",
    email: "info@eventpro.com",
    phoneNumber: "+44 131 456 7890",
    agencyBrief:
      "EventPro Staffing specializes in providing personnel for events of all sizes, from intimate gatherings to large-scale festivals. Our staff are experienced in event management, customer service, and crowd control. We pride ourselves on our ability to adapt to any event scenario, ensuring smooth operations and guest satisfaction.",
    status: "Approved",
    primaryStaff: {
      firstName: "Stella",
      lastName: "Showtime",
      phoneNumber: "+44 7700 900141",
      email: "stella.showtime@eventpro.com",
    },
  },
  {
    agencyName: "IndustriHire",
    address: "202 Factory Lane, Leeds, LS1 1UR",
    email: "contact@industrihire.co.uk",
    phoneNumber: "+44 113 567 8901",
    agencyBrief:
      "IndustriHire is a leading staffing agency for the manufacturing and industrial sectors. We provide skilled workers for production lines, quality control, and machine operation. Our staff undergo rigorous safety training and are well-versed in modern manufacturing processes, helping our clients maintain high productivity and quality standards.",
    status: "Approved",
    primaryStaff: {
      firstName: "Max",
      lastName: "Machinery",
      phoneNumber: "+44 7700 900142",
      email: "max.machinery@industrihire.co.uk",
    },
  },
  {
    agencyName: "TechTalent Recruiters",
    address: "303 Silicon Street, Cambridge, CB2 1TN",
    email: "hello@techtalent.com",
    phoneNumber: "+44 1223 678 901",
    agencyBrief:
      "TechTalent Recruiters specializes in placing IT professionals across various industries. From software developers to network administrators, we connect skilled tech workers with companies at the forefront of innovation. Our thorough vetting process ensures that we provide candidates who are not only technically proficient but also a good cultural fit for our clients.",
    status: "Approved",
    primaryStaff: {
      firstName: "Ada",
      lastName: "Lovelace",
      phoneNumber: "+44 7700 900143",
      email: "ada.lovelace@techtalent.com",
    },
  },
  {
    agencyName: "OfficeWorks Staffing",
    address: "404 Business Park, Bristol, BS1 1EA",
    email: "info@officeworks.co.uk",
    phoneNumber: "+44 117 789 0123",
    agencyBrief:
      "OfficeWorks Staffing provides administrative and clerical staff to businesses of all sizes. From receptionists to executive assistants, our personnel are skilled in office management, communication, and the latest business software. We help keep our clients' offices running smoothly and efficiently.",
    status: "Pending",
    primaryStaff: {
      firstName: "Donna",
      lastName: "Efficient",
      phoneNumber: "+44 7700 900144",
      email: "donna.efficient@officeworks.co.uk",
    },
  },
  {
    agencyName: "ConstructCrew Ltd",
    address: "505 Builder's Way, Glasgow, G1 1BL",
    email: "build@constructcrew.com",
    phoneNumber: "+44 141 890 1234",
    agencyBrief:
      "ConstructCrew Ltd is the premier staffing agency for the construction industry. We supply skilled laborers, certified tradespeople, and project managers for construction projects of all scales. Our staff are fully trained in the latest safety protocols and construction techniques, ensuring quality and compliance on every job site.",
    status: "Approved",
    primaryStaff: {
      firstName: "Bob",
      lastName: "Builder",
      phoneNumber: "+44 7700 900145",
      email: "bob.builder@constructcrew.com",
    },
  },
  {
    agencyName: "EduStaff Solutions",
    address: "606 Classroom Avenue, Oxford, OX1 1ED",
    email: "teach@edustaff.co.uk",
    phoneNumber: "+44 1865 901 234",
    agencyBrief:
      "EduStaff Solutions specializes in placing qualified teachers and support staff in schools across the UK. From supply teachers to long-term placements, we ensure that our educators are not only qualified but also passionate about fostering learning. We work closely with schools to understand their unique needs and culture.",
    status: "Approved",
    primaryStaff: {
      firstName: "Mary",
      lastName: "Poppins",
      phoneNumber: "+44 7700 900146",
      email: "mary.poppins@edustaff.co.uk",
    },
  },
  {
    agencyName: "GreenThumb Gardeners",
    address: "707 Floral Street, Kew, TW9 3AB",
    email: "grow@greenthumb.co.uk",
    phoneNumber: "+44 20 8901 2345",
    agencyBrief:
      "GreenThumb Gardeners provides skilled horticulturists and landscapers to private estates, public parks, and botanical gardens. Our staff have extensive knowledge of plant care, landscape design, and sustainable gardening practices. We're committed to helping our clients create and maintain beautiful, thriving green spaces.",
    status: "Pending",
    primaryStaff: {
      firstName: "Rose",
      lastName: "Bloom",
      phoneNumber: "+44 7700 900147",
      email: "rose.bloom@greenthumb.co.uk",
    },
  },
  {
    agencyName: "MarinePro Personnel",
    address: "808 Harbor Road, Southampton, SO14 3QW",
    email: "sail@marinepro.com",
    phoneNumber: "+44 23 8012 3456",
    agencyBrief:
      "MarinePro Personnel is the leading staffing agency for the maritime industry. We provide qualified crew members for commercial ships, cruise liners, and private yachts. Our personnel are certified in maritime safety and operations, ensuring smooth sailing for all our clients' ventures at sea.",
    status: "Approved",
    primaryStaff: {
      firstName: "Captain",
      lastName: "Nemo",
      phoneNumber: "+44 7700 900148",
      email: "captain.nemo@marinepro.com",
    },
  },
  {
    agencyName: "CreativeCrew Collective",
    address: "909 Artistry Lane, Brighton, BN1 1AR",
    email: "create@creativecrew.co.uk",
    phoneNumber: "+44 1273 123 456",
    agencyBrief:
      "CreativeCrew Collective connects talented artists, designers, and creatives with agencies and businesses in need of creative services. From graphic designers to UX/UI specialists, our network of creative professionals helps bring our clients' visions to life. We foster a community of innovation and artistic excellence.",
    status: "Declined",
    primaryStaff: {
      firstName: "Pablo",
      lastName: "Picasso",
      phoneNumber: "+44 7700 900149",
      email: "pablo.picasso@creativecrew.co.uk",
    },
  },
  {
    agencyName: "SportsPlus Staffing",
    address: "1010 Stadium Way, Manchester, M16 0RA",
    email: "play@sportsplus.com",
    phoneNumber: "+44 161 234 5678",
    agencyBrief:
      "SportsPlus Staffing provides personnel for sporting events, fitness centers, and recreational facilities. From event stewards to personal trainers, our staff are passionate about sports and physical fitness. We ensure that our clients have the right team to make every sporting event and fitness program a success.",
    status: "Approved",
    primaryStaff: {
      firstName: "Usain",
      lastName: "Bolt",
      phoneNumber: "+44 7700 900150",
      email: "usain.bolt@sportsplus.com",
    },
  },
  {
    agencyName: "TechSupport Heroes",
    address: "1111 Circuit Board Street, Reading, RG1 1TS",
    email: "help@techsupport.co.uk",
    phoneNumber: "+44 118 345 6789",
    agencyBrief:
      "TechSupport Heroes provides skilled IT support staff to businesses and organizations. Our technicians are experts in troubleshooting, network maintenance, and user support. We ensure that our clients' technology infrastructure runs smoothly, minimizing downtime and maximizing productivity.",
    status: "Pending",
    primaryStaff: {
      firstName: "Linus",
      lastName: "Torvalds",
      phoneNumber: "+44 7700 900151",
      email: "linus.torvalds@techsupport.co.uk",
    },
  },
  {
    agencyName: "HospitalityPro",
    address: "1212 Welcome Avenue, Bath, BA1 1SV",
    email: "serve@hospitalitypro.com",
    phoneNumber: "+44 1225 456 789",
    agencyBrief:
      "HospitalityPro is dedicated to staffing the hospitality industry with top-tier professionals. From hotel receptionists to event coordinators, our staff are trained in the art of customer service and hospitality management. We help our clients create memorable experiences for their guests, ensuring satisfaction and repeat business.",
    status: "Approved",
    primaryStaff: {
      firstName: "Jeeves",
      lastName: "Butler",
      phoneNumber: "+44 7700 900152",
      email: "jeeves.butler@hospitalitypro.com",
    },
  },
];

const singleJobSeeker = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "+44 7123 456789",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    dateOfBirth: "1990-05-15",
    aboutMe:
      "Experienced software developer with a passion for creating efficient and scalable applications. Skilled in React, Node.js, and Python. Always eager to learn new technologies and contribute to innovative projects. I thrive in collaborative environments and enjoy solving complex problems.",
    totalJobsDone: 15,
    withAgency: false,
    totalHoursWorked: 2500,
    lastActiveDate: "2024-08-10",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "A1B2C3D4",
      expiryDate: "2024-09-13",
    },
  },
  // ... (add 19 more similar objects with varied data)
];

// const generateRandomJobSeeker = (id) => {
//   const statuses = ["Onboarded", "Not onboarded", "Applied", "Invitation Sent"];
//   const firstNames = [
//     "Emma",
//     "Liam",
//     "Olivia",
//     "Noah",
//     "Ava",
//     "Ethan",
//     "Sophia",
//     "Mason",
//     "Isabella",
//     "William",
//   ];
//   const lastNames = [
//     "Smith",
//     "Johnson",
//     "Brown",
//     "Taylor",
//     "Miller",
//     "Wilson",
//     "Moore",
//     "Anderson",
//     "Thomas",
//     "Jackson",
//   ];

//   return {
//     id,
//     firstName: firstNames[Math.floor(Math.random() * firstNames.length)],
//     lastName: lastNames[Math.floor(Math.random() * lastNames.length)],
//     email: `${firstNames[
//       Math.floor(Math.random() * firstNames.length)
//     ].toLowerCase()}.${lastNames[
//       Math.floor(Math.random() * lastNames.length)
//     ].toLowerCase()}@example.com`,
//     phoneNumber: `+44 ${Math.floor(Math.random() * 10000000000)
//       .toString()
//       .padStart(10, "0")}`,
//     profilePicture: `https://randomuser.me/api/portraits/${
//       Math.random() > 0.5 ? "men" : "women"
//     }/${id}.jpg`,
//     dateOfBirth: new Date(
//       1970 + Math.floor(Math.random() * 30),
//       Math.floor(Math.random() * 12),
//       Math.floor(Math.random() * 28) + 1
//     )
//       .toISOString()
//       .split("T")[0],
//     aboutMe: "Professional with diverse skills and experience in the industry.",
//     totalJobsDone: Math.floor(Math.random() * 50),
//     withAgency: Math.random() > 0.5,
//     totalHoursWorked: Math.floor(Math.random() * 5000),
//     lastActiveDate: new Date(
//       Date.now() - Math.floor(Math.random() * 30) * 24 * 60 * 60 * 1000
//     )
//       .toISOString()
//       .split("T")[0],
//     documents: [
//       {
//         name: "CV",
//         lastUpdated: "2024-07-01",
//         url: "https://example.com/cv.pdf",
//       },
//       {
//         name: "International Passport",
//         lastUpdated: "2023-12-15",
//         url: "https://example.com/passport.pdf",
//       },
//       {
//         name: "BRP",
//         lastUpdated: "2024-01-10",
//         url: "https://example.com/brp.pdf",
//       },
//       {
//         name: "National Insurance",
//         lastUpdated: "2024-02-20",
//         url: "https://example.com/ni.pdf",
//       },
//     ],
//     shareCode: {
//       code: Math.random().toString(36).substring(2, 10).toUpperCase(),
//       expiryDate: new Date(
//         Date.now() + Math.floor(Math.random() * 30) * 24 * 60 * 60 * 1000
//       )
//         .toISOString()
//         .split("T")[0],
//     },
//     agencyStatus: statuses[Math.floor(Math.random() * statuses.length)],
//   };
// };

// Generate 25 job seekers
// const jobSeekers = Array.from({ length: 25 }, (_, i) =>
//   generateRandomJobSeeker(i + 1)
// );

const jobSeekers = [
  {
    id: 1,
    firstName: "Mason",
    lastName: "Miller",
    email: "sophia.brown@example.com",
    phoneNumber: "+44 3531003945",
    profilePicture: "https://randomuser.me/api/portraits/women/1.jpg",
    dateOfBirth: "1984-09-07",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 13,
    withAgency: false,
    totalHoursWorked: 4345,
    lastActiveDate: "2024-07-28",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "D0EVAYWA",
      expiryDate: "2024-09-09",
    },
    agencyStatus: "Onboarded",
  },
  {
    id: 2,
    firstName: "Noah",
    lastName: "Thomas",
    email: "ava.thomas@example.com",
    phoneNumber: "+44 8312508361",
    profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    dateOfBirth: "1994-01-15",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 33,
    withAgency: true,
    totalHoursWorked: 441,
    lastActiveDate: "2024-08-12",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "70V9V9QD",
      expiryDate: "2024-09-06",
    },
    agencyStatus: "Invitation Sent",
  },
  {
    id: 3,
    firstName: "Sophia",
    lastName: "Thomas",
    email: "mason.moore@example.com",
    phoneNumber: "+44 1118290468",
    profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    dateOfBirth: "1976-05-22",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 13,
    withAgency: false,
    totalHoursWorked: 27,
    lastActiveDate: "2024-08-07",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "MR0VB6MX",
      expiryDate: "2024-08-21",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 4,
    firstName: "Mason",
    lastName: "Anderson",
    email: "olivia.thomas@example.com",
    phoneNumber: "+44 2064859422",
    profilePicture: "https://randomuser.me/api/portraits/men/4.jpg",
    dateOfBirth: "1975-02-09",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 9,
    withAgency: false,
    totalHoursWorked: 3836,
    lastActiveDate: "2024-07-24",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "7PUKM44O",
      expiryDate: "2024-09-11",
    },
    agencyStatus: "Onboarded",
  },
  {
    id: 5,
    firstName: "Ava",
    lastName: "Moore",
    email: "ethan.moore@example.com",
    phoneNumber: "+44 7910137055",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    dateOfBirth: "1979-09-22",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 4,
    withAgency: false,
    totalHoursWorked: 4425,
    lastActiveDate: "2024-07-26",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "99KRNCRE",
      expiryDate: "2024-09-10",
    },
    agencyStatus: "Applied",
  },
  {
    id: 6,
    firstName: "Olivia",
    lastName: "Moore",
    email: "ethan.johnson@example.com",
    phoneNumber: "+44 9216010885",
    profilePicture: "https://randomuser.me/api/portraits/men/6.jpg",
    dateOfBirth: "1982-06-04",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 4,
    withAgency: true,
    totalHoursWorked: 1824,
    lastActiveDate: "2024-08-11",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "4C6O5VO2",
      expiryDate: "2024-08-29",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 7,
    firstName: "Mason",
    lastName: "Brown",
    email: "ethan.smith@example.com",
    phoneNumber: "+44 8275404367",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    dateOfBirth: "1989-03-25",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 27,
    withAgency: true,
    totalHoursWorked: 4587,
    lastActiveDate: "2024-07-15",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "AHOI4WGU",
      expiryDate: "2024-09-07",
    },
    agencyStatus: "Applied",
  },
  {
    id: 8,
    firstName: "Noah",
    lastName: "Johnson",
    email: "ethan.jackson@example.com",
    phoneNumber: "+44 5233689415",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    dateOfBirth: "1999-04-03",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 18,
    withAgency: false,
    totalHoursWorked: 3840,
    lastActiveDate: "2024-08-08",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "YJRKO2IG",
      expiryDate: "2024-09-05",
    },
    agencyStatus: "Invitation Sent",
  },
  {
    id: 9,
    firstName: "Liam",
    lastName: "Johnson",
    email: "sophia.brown@example.com",
    phoneNumber: "+44 4368956704",
    profilePicture: "https://randomuser.me/api/portraits/women/9.jpg",
    dateOfBirth: "1991-04-16",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 38,
    withAgency: true,
    totalHoursWorked: 27,
    lastActiveDate: "2024-08-10",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "A62HZ50S",
      expiryDate: "2024-08-27",
    },
    agencyStatus: "Invitation Sent",
  },
  {
    id: 10,
    firstName: "William",
    lastName: "Miller",
    email: "isabella.wilson@example.com",
    phoneNumber: "+44 5908034982",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    dateOfBirth: "1998-04-27",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 0,
    withAgency: true,
    totalHoursWorked: 4650,
    lastActiveDate: "2024-08-04",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "KHR98F81",
      expiryDate: "2024-09-09",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 11,
    firstName: "Noah",
    lastName: "Anderson",
    email: "mason.miller@example.com",
    phoneNumber: "+44 6612647114",
    profilePicture: "https://randomuser.me/api/portraits/women/11.jpg",
    dateOfBirth: "1984-01-28",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 21,
    withAgency: true,
    totalHoursWorked: 4095,
    lastActiveDate: "2024-08-05",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "ZW3VZO8G",
      expiryDate: "2024-09-05",
    },
    agencyStatus: "Applied",
  },
  {
    id: 12,
    firstName: "Isabella",
    lastName: "Moore",
    email: "mason.brown@example.com",
    phoneNumber: "+44 5474646619",
    profilePicture: "https://randomuser.me/api/portraits/men/12.jpg",
    dateOfBirth: "1987-05-19",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 37,
    withAgency: false,
    totalHoursWorked: 438,
    lastActiveDate: "2024-07-30",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "U4K0VEP6",
      expiryDate: "2024-08-13",
    },
    agencyStatus: "Onboarded",
  },
  {
    id: 13,
    firstName: "Noah",
    lastName: "Wilson",
    email: "noah.anderson@example.com",
    phoneNumber: "+44 8030419531",
    profilePicture: "https://randomuser.me/api/portraits/women/13.jpg",
    dateOfBirth: "1984-03-23",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 18,
    withAgency: true,
    totalHoursWorked: 2805,
    lastActiveDate: "2024-07-21",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "QY978TFQ",
      expiryDate: "2024-09-08",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 14,
    firstName: "Ava",
    lastName: "Smith",
    email: "noah.miller@example.com",
    phoneNumber: "+44 6085348989",
    profilePicture: "https://randomuser.me/api/portraits/women/14.jpg",
    dateOfBirth: "1970-08-06",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 3,
    withAgency: false,
    totalHoursWorked: 878,
    lastActiveDate: "2024-07-28",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "VA6F9HYW",
      expiryDate: "2024-08-26",
    },
    agencyStatus: "Applied",
  },
  {
    id: 15,
    firstName: "Isabella",
    lastName: "Moore",
    email: "noah.anderson@example.com",
    phoneNumber: "+44 3873081825",
    profilePicture: "https://randomuser.me/api/portraits/men/15.jpg",
    dateOfBirth: "1973-09-18",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 21,
    withAgency: false,
    totalHoursWorked: 713,
    lastActiveDate: "2024-07-16",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "ZBHU0LWR",
      expiryDate: "2024-08-13",
    },
    agencyStatus: "Invitation Sent",
  },
  {
    id: 16,
    firstName: "Ethan",
    lastName: "Thomas",
    email: "william.smith@example.com",
    phoneNumber: "+44 6743729490",
    profilePicture: "https://randomuser.me/api/portraits/men/16.jpg",
    dateOfBirth: "1992-05-23",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 28,
    withAgency: true,
    totalHoursWorked: 399,
    lastActiveDate: "2024-08-03",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "3DH28D4L",
      expiryDate: "2024-09-03",
    },
    agencyStatus: "Onboarded",
  },
  {
    id: 17,
    firstName: "Olivia",
    lastName: "Taylor",
    email: "mason.taylor@example.com",
    phoneNumber: "+44 4993597976",
    profilePicture: "https://randomuser.me/api/portraits/men/17.jpg",
    dateOfBirth: "1972-09-20",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 23,
    withAgency: true,
    totalHoursWorked: 3486,
    lastActiveDate: "2024-07-24",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "AQUK4U63",
      expiryDate: "2024-09-04",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 18,
    firstName: "Liam",
    lastName: "Anderson",
    email: "william.taylor@example.com",
    phoneNumber: "+44 1119754012",
    profilePicture: "https://randomuser.me/api/portraits/women/18.jpg",
    dateOfBirth: "1991-12-18",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 24,
    withAgency: true,
    totalHoursWorked: 987,
    lastActiveDate: "2024-08-11",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "KFTN437X",
      expiryDate: "2024-08-30",
    },
    agencyStatus: "Applied",
  },
  {
    id: 19,
    firstName: "Emma",
    lastName: "Thomas",
    email: "sophia.wilson@example.com",
    phoneNumber: "+44 4027737797",
    profilePicture: "https://randomuser.me/api/portraits/women/19.jpg",
    dateOfBirth: "1986-08-06",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 49,
    withAgency: false,
    totalHoursWorked: 2957,
    lastActiveDate: "2024-08-02",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "Y1F88KQA",
      expiryDate: "2024-08-28",
    },
    agencyStatus: "Applied",
  },
  {
    id: 20,
    firstName: "Olivia",
    lastName: "Smith",
    email: "ethan.johnson@example.com",
    phoneNumber: "+44 8782060544",
    profilePicture: "https://randomuser.me/api/portraits/men/20.jpg",
    dateOfBirth: "1990-11-02",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 42,
    withAgency: true,
    totalHoursWorked: 2251,
    lastActiveDate: "2024-07-18",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "GEM83OG9",
      expiryDate: "2024-08-24",
    },
    agencyStatus: "Applied",
  },
  {
    id: 21,
    firstName: "William",
    lastName: "Brown",
    email: "olivia.johnson@example.com",
    phoneNumber: "+44 8580988618",
    profilePicture: "https://randomuser.me/api/portraits/women/21.jpg",
    dateOfBirth: "1996-01-04",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 42,
    withAgency: false,
    totalHoursWorked: 1413,
    lastActiveDate: "2024-07-30",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "9P1H3EKS",
      expiryDate: "2024-08-16",
    },
    agencyStatus: "Onboarded",
  },
  {
    id: 22,
    firstName: "Liam",
    lastName: "Jackson",
    email: "william.moore@example.com",
    phoneNumber: "+44 1506778407",
    profilePicture: "https://randomuser.me/api/portraits/men/22.jpg",
    dateOfBirth: "1991-11-11",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 11,
    withAgency: false,
    totalHoursWorked: 3794,
    lastActiveDate: "2024-08-09",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "QJZUOCV9",
      expiryDate: "2024-09-09",
    },
    agencyStatus: "Not onboarded",
  },
  {
    id: 23,
    firstName: "Isabella",
    lastName: "Wilson",
    email: "isabella.jackson@example.com",
    phoneNumber: "+44 5541767758",
    profilePicture: "https://randomuser.me/api/portraits/women/23.jpg",
    dateOfBirth: "1970-10-07",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 28,
    withAgency: false,
    totalHoursWorked: 2017,
    lastActiveDate: "2024-07-15",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "HN5Z7RC9",
      expiryDate: "2024-09-05",
    },
    agencyStatus: "Applied",
  },
  {
    id: 24,
    firstName: "Isabella",
    lastName: "Thomas",
    email: "noah.brown@example.com",
    phoneNumber: "+44 5448827326",
    profilePicture: "https://randomuser.me/api/portraits/men/24.jpg",
    dateOfBirth: "1998-11-19",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 13,
    withAgency: true,
    totalHoursWorked: 2985,
    lastActiveDate: "2024-07-30",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "IZNFZPCE",
      expiryDate: "2024-08-15",
    },
    agencyStatus: "Applied",
  },
  {
    id: 25,
    firstName: "Isabella",
    lastName: "Thomas",
    email: "mason.moore@example.com",
    phoneNumber: "+44 9938936141",
    profilePicture: "https://randomuser.me/api/portraits/women/25.jpg",
    dateOfBirth: "1978-01-13",
    aboutMe: "Professional with diverse skills and experience in the industry.",
    totalJobsDone: 25,
    withAgency: false,
    totalHoursWorked: 2254,
    lastActiveDate: "2024-07-24",
    documents: [
      {
        name: "CV",
        lastUpdated: "2024-07-01",
        url: "https://example.com/cv.pdf",
      },
      {
        name: "International Passport",
        lastUpdated: "2023-12-15",
        url: "https://example.com/passport.pdf",
      },
      {
        name: "BRP",
        lastUpdated: "2024-01-10",
        url: "https://example.com/brp.pdf",
      },
      {
        name: "National Insurance",
        lastUpdated: "2024-02-20",
        url: "https://example.com/ni.pdf",
      },
    ],
    shareCode: {
      code: "CRIAS3DR",
      expiryDate: "2024-08-20",
    },
    agencyStatus: "Applied",
  },
];

export {
  jobsList,
  staffList,
  agencies,
  generateJobSeekers,
  singleJobSeeker,
  jobSeekers,
};
