name:  CONNECT API .NET

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure, success'
        notification_title:  ${{ github.event.head_commit.author.name }} don push to '{branch}'
        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}|branch> ${{ github.event.head_commit.message }}'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
#           notify_when: 'failure'
        mention_users: 'U037BKFR0HX'
        mention_users_when: 'failure'
#           mention_groups: ''
#           mention_groups_when: 'failure,warnings'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - uses: actions/checkout@v3

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v2
#       with:
#         dotnet-version: 6.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal

    - name: Staging Release Connect API
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FI_LAB_SERVER }}
        username: ${{ secrets.FI_LAB_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.FI_LAB_PORT }}
        script: |
           cd /usr/staging-projects/fi-staging-projects/Connect-Backend-API
           git pull origin dev
           docker build -t connectapi .
           docker rm -f connectapi || true
           docker run --name connectapi --restart always -d -p 3437:80 -e ASPNETCORE_ENVIRONMENT=Development connectapi

